bazelbuild/rules_android_ndk

- BUILD.ndk_clang.tpl
These are produced by the native NDK setup, and seem to be required for multi-language builds like building rust for Android. These are used by passing `--extra_toolchains=@androidndk//...` to bazel when targeting Android.
> Add toolchain definitions for cc_toolchains

- ndk_cc_toolchain_config.bzl
This is part of https://github.com/bazelbuild/rules_android_ndk/issues/5
Users who want this should set `build --cxxopt=-fno-exceptions` in their `.bazelrc`
> Remove -fno-exceptions default

- ndk_cc_toolchain_config.bzl
For folks who want this always they should set `build --features=warnings_as_errors` in their `.bazelrc`
This is part of https://github.com/bazelbuild/rules_android_ndk/issues/5
> Disable warnings_as_errors by default

- .bazelci/presubmit.yml
This should unblock LTS cut of Bazel.
Related to: https://github.com/bazelbuild/rules_android_ndk/issues/21
> Disable cc_toolchain_resolution

- rules.bzl
Reading and accepting `ANDROID_NDK_HOME` over the provided path results in some misleading errors where the `rules_android_ndk` repo will completely ignore any `path` value that you pass during setup.
> Use path attr before ANDROID_NDK_HOME

- BUILD.ndk_clang.tpl
- BUILD.ndk_root.tpl
- BUILD.ndk_sysroot.tpl
- rules.bzl
- target_systems.bzl.tpl
This is work towards enabling platforms and toolchains for Android builds (https://github.com/bazelbuild/bazel/issues/16285).
> Update `android_ndk_repository` to also register the CC toolchains.

- .bazelci/presubmit.yml
- BUILD.ndk_root.tpl
- examples/cpu_features/BUILD
- examples/cpu_features/README.md
- examples/cpu_features/WORKSPACE
- examples/cpu_features/jni.cc
- examples/cpu_features/jni_cpu_features_compat.cc
- rules.bzl
Also adds tests, and a note about using https://github.com/google/cpu_features instead of the cpu_features target defined by android_ndk_repository.
> Enables backwards compatibility with include paths prefixed with "ndk/"

- .bazelci/presubmit.yml
- BUILD.ndk_clang.tpl
- BUILD.ndk_sysroot.tpl
In order to flip the flag, all downstream projects should be adapted. However, it is hard to fix them all if there are constant regressions. Adding it to the CI will ensure that once the project can build with incompatible_disallow_empty_glob it can keep building like that.
See: bazelbuild/bazel#15327
> Build with incompatible_disallow_empty_glob

- ndk_cc_toolchain_config.bzl
Bazel has some custom features for allowing users to enable / disable pic. As far as I can tell Android requires pic executables for a while. The easiest way to force this always is to ignore bazel's custom pic support and just always pass the `-fPIC` compiler flag. This avoids issues where other rulesets cannot easily know if pic should be enabled, and accidentally compile things without pic, leading to linker failures. Specifically I hit https://github.com/bazelbuild/rules_foreign_cc/issues/421
This is pretty similar to what iOS does as well where it just forces the pic feature on always https://github.com/bazelbuild/bazel/blob/24dbe0de1831697758c5732bc4210e75c7187393/tools/osx/crosstool/cc_toolchain_config.bzl#L1099-L1117
> Remove bazel pic features

- WORKSPACE
The `WORKSPACE` file is missing the default workspace name.
> Add name to repo WORKSPACE

- rules.bzl
This is the recommendation from the NDK folks to be future proof.
> Use clang --print-resource-dir for discovery

- BUILD.ndk_clang.tpl
- BUILD.ndk_sysroot.tpl
The current NDK 26 beta moves a significant number of files from previous versions. lib64 no longer exists and everything is nested inside of lib/ instead. Some libraries were also removed.
> Update to support NDK 26

- rules.bzl
of `--android_crosstool_top` works.
> Add a binding for external/android/crosstool so that the default value

- rules.bzl
Otherwise, the rule evaluation restarts every time it encounters a new `Label()` to resolve.
Also includes the change from #58 (generate `BUILD.bazel` instead of just `BUILD`).
> Use attr.label to load template files

- README.md
- examples/basic/WORKSPACE
- examples/cpu_features/WORKSPACE
- rules.bzl
This enables using `--extra_toolchains` on specific platforms, which is helpful when building a monorepo that has platforms without the Android SDK/NDK available.
Without this, it's impossible to use these rules if you're planning in a system where the NDK is unavailable (or not installed).
> Let users declare repository without registering the toolchain

- .bcr/config.yml
- .bcr/metadata.template.json
- .bcr/presubmit.yml
- .bcr/source.template.json
Adding BCR configs to start publishing rules_android_ndk to the Bazel Central Registry.
> Add .bcr configs for publishing to the central registry

- README.md
- rules.bzl
This makes it possible to reference the NDK path if it exists within the workspace. Using `--repo_env ANDROID_NDK_HOME=` for different OS platforms makes it possible to change the path for different configurations.
> Support relative workspace paths

- examples/basic/MODULE.bazel
- examples/basic/WORKSPACE
- extension.bzl
... to address rules_android_ndk bazelCI failure.
`buildifier -v -r .`
> Run buildifier on all starlark sources

- BUILD.ndk_clang.tpl
tl;dr : the issue description and repro: https://github.com/gdevillele/debug_bazel
I am trying to build native C libs for Android using Bazel and `rules_android_ndk`, and am getting the following error:
```
glob pattern 'lib64/**/*' didn't match anything, but allow_empty is set to False
```
This is due to a breaking change introduced in Bazel 8.0.
(https://github.com/bazelbuild/bazel/issues/8195)
Note: I am still a beginner with Bazel, so let me know if this is not the correct way of fixing this.
Thank you 🙂
> fix empty glob() error

- rules.bzl
From [here](https://bazel.build/rules/lib/builtins/repository_os.html#environ), seems like `ctx.os.environ` doesn't establish a dependency from the repository rule to the environment variable. It seems like we want the dependency here.
> Use `ctx.getenv` to get NDK home
